print("Hello, World!!!")
print("Hello, Again!")
print("I like typing this.")
print("This is fun.")
print('Yay! Printing...')
# print("I'd much ruther you 'not'.")
print('I "said" do not touch this.')
print("I am John Wayne.")
